### ISSUE TITLE
Montar o time do CDC da PyBR

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#100]
Aguardando guidelines da @pythonbrasil/apyb

**Comment by cecivieira** [comment]
@anicelysantos acho que tás trabalhando nessa nova versão da documentação, né?
Como está isso?

**Comment by anicelysantos** [comment]
Está avançando, mas ainda falta bastante coisa. É possível que esteja concluído entre este mês o próximo.

**Comment by allanacardoso** [comment]
@anicelysantos precisa de contribuição no CDC? Se sim me dá um toque no zap, Telegram ou insta que eu te ajudo!

**Comment by biancarosa** [comment]
eu criei essa issue aqui pra aguardar a @andressalf com essas docs novas!

não é uma issue urgente, podemos ter tudo pronto até 1 semana antes do evento,seria legal ter até 1 mês antes! 

Andressa me pediu até próxima sexta-feira mais ou menos pra organizar algumas coisas e ver se ela consegue ir na pybr tb.

**Comment by anicelysantos** [comment]
@allanacardoso  siim, pode chegar! @AndressaLF tá puxando este GT. Vou dá um toque nela pra chegar por aqui e dá os direcionamentos.

**Comment by AndressaLF** [comment]
> @anicelysantos acho que tás trabalhando nessa nova versão da documentação, né? Como está isso?

Estamos editando a documentação, reabri uma antiga issue que discutia a criação de um GT([issue 55](https://github.com/apyb/comunidade/discussions/55)) com o objetivo de reunirmos mais nomes para contribuição desse documento. 

**Quem quiser e puder contribuir pode entrar em contato para ter acesso ao documento.**

**Comment by AndressaLF** [comment]
> eu criei essa issue aqui pra aguardar a @AndressaLF com essas docs novas!
> 
> não é uma issue urgente, podemos ter tudo pronto até 1 semana antes do evento,seria legal ter até 1 mês antes!
> 
> Andressa me pediu até próxima sexta-feira mais ou menos pra organizar algumas coisas e ver se ela consegue ir na pybr tb.

Tenho interesse de ir para a PyBR24 para contribuir com a equipe de respostas, preenchi o formulário dos ingressos solidários.
Acredito que a documentação não deve estar finalizada até lá e pelo tempo até o evento acredito que a Equipe precisa ser montada o quanto antes, estou a disposição para ajudar nesse processo também caso seja necessário.

**Comment by cecivieira** [comment]
Citando aqui a iniciativa do GT que tá rolando no "discussion" da comunidade:
https://github.com/apyb/comunidade/discussions/55#discussioncomment-10330976

**Comment by biancarosa** [comment]
A PyBR precisa de uma equipe de resposta independente do GT, e hoje a responsabilidade de escolher alguém pra liderar essa equipe tá comigo por isso me dei assign aqui.

Minha intenção é que seja alguém que já tenha experiência com CDC e em conversa presencial com a Andressa, dada a vontade dela de criar essas guidelines de trabalho nesse GT da APyB, eu acho que ela é uma pessoa boa para liderar essa equipe.

No momento o que temos que fazer aqui é esperar a poeira baixar um pouco, a gente chegar em casa pós PyNE, e vermos se isso é possível e viável. Em duas semanas max devemos ter isso decidido e aí eu dou reassign aqui pra pessoa lider do time :D

**Comment by cecivieira** [comment]
Acredito que @AndressaLF e @anicelysantos já tem conhecimento desse protocolo que foi criado há poucos anos:
https://github.com/pythonbrasil/pybr2022-org/tree/main/protocolos. Cito ele para contribuir na redação do atual.
