### ISSUE TITLE
Documentar reunião com o local do evento

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#103]
- Acessibilidade
- Banheiros
- Transmissão
- Live coding
- Mobiliario de sala
- Entrada no local: restricoes, chinelo bermuda etc.
- Brindes pros participantes (pode ser algo de comida?)
- Banner credentiamento decoração
- 4g la embaixo?

**Comment by biancarosa** [comment]
falta: bia resumir a reunião

**Comment by thaisviana** [comment]
foi feito falado em reunião.
