### ISSUE TITLE
Selecionar as palestras para o evento

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#106]
### Descrição

- Criar um grupo e coordenar as tarefas para garantir a seleção de palestras da PyBR até (idealmente) 1-10 de setembro.
- Responsável: @anadulce 
- Voluntarios: Marcos, Mari, Jules

- Votação comunidade: vamos ter ou não? Poderiamos ter um time de pessoas revisoras.
- Preocupações: definir os critérios exatos, nossas metas de diversidade, pensar numa nota de corte pra palestras de forma que consigamos bater essas metas + ter as palestras de qualidade e também pensar em como pode ser mais desafiador palestrar em formato arena e oferecer algum tipo de mentoria.

### Requisitos para a atividade ser considerada como concluída

- Grade publicada no pretalx :)

**Comment by anadulce** [comment]
Reports aqui:
* Seguindo o [modelo sugerido pelo Gabriel e pelo Rougeth](https://rgth.co/pt-br/blog/modelo-de-avaliacao-das-atividades-da-python-brasil/), no dia 25 de agosto, convidamos as pessoas proponentes para a avaliação das atividades (e também algumas pessoas da organização e voluntários).
* Essa avaliação será realizada até o dia 31 de setembro. No dia 01 de setembro, teremos uma reunião síncrona do time de seleção de atividades, e com base nas notas e critérios de diversidade de temas e de pessoas, selecionaremos as atividades que integrarão a programação da Python Brasil.
