### ISSUE TITLE
Reservar hotel para keynote

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#107]
### Descrição
 
Entrar em contato com um dos hotéis e reservar para um keynote. Confirmar as datas no e-mail de confirmação de palestra.

**Comment by biancarosa** [comment]
17-21 de outubro

**Comment by rochamrcs** [comment]
Aguardando envio da RPS para solicitar pagamento, a princípio a reserva está confirmada

**Comment by rochamrcs** [comment]
Pagamento confirmado e email de confirmação enviado ao keynote
