### ISSUE TITLE
[Financeiro] Fechar coffee break

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#11]
Entrar em contato com a Joá Gastronomia.
Orçamento: https://drive.google.com/file/d/1O7l6qx2sEp8ywEKZVZw8-JimzuW17Ceu/view?usp=drive_link

Temos a possibilidade de fazer apenas um coffee por dia na parte da tarde, pra ~500-600 pessoas.
Verificar a possibilidade de termos café durante o dia.
Orçar bebedouro.
Pedir garrafas termicas para deixar lá.
Alguns itens de comida como brinde - mate distribuido pelo evento etc.

**Comment by jamesperes** [comment]
Dois por dia:
 - Manha 
 - Tarde 
 
 Bebidas:
 - Sucos
 - Café 
 - Refrigerante

- Ter comidas Veganas / Vegetarianas


Verificar a possibilidade de almoço ( Dependência do local).
 - Quentinhas 
 - Almoço completo.

**Comment by jamesperes** [comment]
emails enviados

**Comment by biancarosa** [comment]
Como fechamos com o local que tem venda casada com coffee break, já temos o orçamento. Vamos fechar chegando mais perto.

**Comment by cecivieira** [comment]
Qual das opções que vamos escolher para o coffee?

Orçamento: https://drive.google.com/file/d/1O7l6qx2sEp8ywEKZVZw8-JimzuW17Ceu/view?usp=drive_link

**Comment by biancarosa** [comment]
Eu iria com a opção (1), e entenderia que outros tipos de coisas fora do coffee podemos oferecer por fora (biscoitos etc). Não acho que o valor justifique um chocolate com ovomaltine, uma opção de quente e uma opção de mini-sanduiche.

**Comment by thaisviana** [comment]
[J835_2_ASSOC.PYTHON_BRASIL_CCBR_ORC_CB_18_A_20OUT_%282%29_assinado.pdf](https://github.com/user-attachments/files/16872075/J835_2_ASSOC.PYTHON_BRASIL_CCBR_ORC_CB_18_A_20OUT_.282.29_assinado.pdf)

Definir data de pagamento nos moldes do contrato:

Os serviços contratados deverão ser quitados, como segue:
[ ] 50% na aprovação da proposta
[ ]  50% 05 dias antes da data do evento
[ ] Extras (se houver) até 05 dias após o evento.

obs Pagamento através de depósito bancário. Os dados bancários serão enviados junto com a
NF.

Valores:

Dia 18 – Coffee Break – R$ 22.200,00
Dia 19 – Coffee Break – R$ 22.200,00
Dia 20 – Coffee Break – R$ 22.200,00
EXTRAS – R$ 4.545,00
TOTAL – R$ 71.145,00

**Comment by cecivieira** [comment]
@thaisviana sugiro que esse contrato seja colocado no drive do evento, conforme organização que Bia tá fazendo.

A organização é responsável por solicitar o pagamento de cada parcela através do preenchimento deste formulário: https://www.ultradox.com/app/apyb-solicitacao-pagamento

**Comment by biancarosa** [comment]
@cecivieira então pra deixar claro - já temos contrato assinado pelas duas partes, já podemos solicitar o pagamento através do form da apyb?

@thaisviana vc consegue preencher esse form ou quer que eu preencha?

**Comment by thaisviana** [comment]
@biancarosa o preenchimento é pós emissão de nota fiscal pelo lado deles ... mas eu faço sim, pode deixar!
Pedi pra enrolar até o dia 20 de setembro.

**Comment by biancarosa** [comment]
=D

**Comment by thaisviana** [comment]
NF 1731  com vencimentos para:
20/09/24 - R$ 35,572,50
já enviado no form da apyb
