### ISSUE TITLE
Horário e sala para assembleia da apyb

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#110]
@tiidadavena posso te explicar melhor o layout do local - mas pra termos uma assembleia bonitinha acho que o ideal seria alugarmos uma das salas conjugadas (valor diário, individual, de 3900 por sala, formato auditório, capacidade para 60 pessoas).

aí precisamos ver se temos que contratar algo mais (transmissão etc). se precisar, posso pedir um orçamento para isso.

**Comment by naanadr** [comment]
@biancarosa mas ai a assembleia iria acontecer no mesmo horário das palestras? porque estávamos pensando que o melhor seria ter na grade apenas a assembleia, como forma de trazer mais pessoas para ela. 

outra dúvida, o evento terá transmissão ao vivo e link dedicado de rede? porque precisamos dessa informação para saber se temos condições de fazer uma assembleia hibrida.

**Comment by biancarosa** [comment]
@naanadr seria bom marcarmos uma reunião sobre a assembleia da apyb com a org da pybr - pelo menos eu, @thaisviana e @rochamrcs :)

a idéia que tivemos seria de ser no mesmo horário sim,  acho que não faz sentido ter um palco trilha unica com 600 pessoas aonde só 100-200 conhecem a apyb pra fazer uma assembléia que historicamente é uma bagunça rs

temos transmissão ao vivo e link dedicado de rede pro palco principal, podemos orçar para uma sala separada se for o caso.

**Comment by biancarosa** [comment]
a gente poderia fazer em um dos momentos de abertura do evento (9am) no palco principal. acho que no domingo não tem nada planejado nssse horário. vamos ter que ser muito chatos com horário se for esse o caso 😅

**Comment by naanadr** [comment]
ser no palco principal pelo visto iria ser menos custoso 🤔 mas antes da gente bater o martelo, @biancarosa vocês conseguem orçar quanto seria essa sala extra e mais um ponto de rede?

**Comment by cecivieira** [comment]
Não acho uma boa ideia colocar a assembleia no palco principal. Caso isso ocorra, seria interessante ser no sábado. Domingo eu não estarei no evento.

**Comment by tiidadavena** [comment]
Não acho bom que a assembleia ocorra no palco principal. Sobre ser num horário de palestras, não vejo problema. Só preciso salientar que caso o quórum não seja atingido de primeira, terão chamadas a cada 30min até que o quantitativo mínimo de associades esteja presente.

**Comment by tiidadavena** [comment]
A transmissão não precisa ser para o palco principal, mas o evento terá quantas trilhas?

**Comment by cecivieira** [comment]
O evento será de trilha única.

**Comment by tiidadavena** [comment]
Segue ata da reunião realizada em conjunto com a @pythonbrasil/pybr2024-org e @apyb/diretoria no dia 08/09/2024:  https://hackmd.io/IuyxvxIQQwuCuDBW5xgVqw

**Comment by tiidadavena** [comment]
Segue ata da reunião realizada em conjunto com a @pythonbrasil/pybr2024-org e @apyb/diretoria no dia 08/09/2024:  https://hackmd.io/IuyxvxIQQwuCuDBW5xgVqw

**Comment by naanadr** [comment]
A assembleia será online no mês que vem.
