### ISSUE TITLE
Votar orçamento para Happy Hour / Algorave no Galpão Ladeira das Artes

### ISSUE THREAD

**Issue by diegodukao** [pythonbrasil/pybr2024-org#111]
Conversei com o Léo do Galpão Ladeira das Artes sobre a possibilidade de fazer o Happy Hour e a Algorave lá. Segue abaixo a resposta dele e o orçamento.

https://www.instagram.com/ladeiradasartes/
Endereço: R. Conselheiro Lampreia, 225 - Cosme Velho

> - essa parte de som que usamos em show é meio que terceirizada, não é nossa, daí em eventos privados não podemos usar. Tem a possibilidade de alugar com eles, daí precisaria me dizer certinho o que precisaria, trazer por fora ou usar um som que temos aqui que tem bluetooth mas é algo mais simples, não tão alto. 
> 
> - temos projetor e tela que daria para emprestar sim
> 
> - questão de horário, não podemos ultrapassar as 23h, e a música (dependendo do volume) precisa terminar as 22h. Então vou colocar aqui no orçamento 18h as 23h blz?

 
**Orçamento encontro Python**

- Entre 17 e 20 de outubro (temos todas as datas)
- 18h as 23h
- 300 pessoas (limite máximo)
- Gramado incluído (pela quantidade de pessoas teria que abrir)
- Bar da casa (não poderia trazer bebida de fora)
- 1 segurança incluído 
- 2 responsáveis pela casa 
- 1 responsável pela limpeza

Valor: 2500

**Comment by biancarosa** [comment]
conversamos na última reunião - todo mundo super topa ajudar.

vamos tentar buscar uma empresa "sponsor" pra algorave - porque sair do orçamento do evento hoje, agora, é inviável, mas a realidade pode mudar 😅

**Comment by thaisviana** [comment]
Vinta esta esperando ver quais palestras serão aprovadas.

Opções: 
0 - Patrocinador de happy hour (vinta ou jus ...)
1 - Campanha de financiamento por fora.
2 - Colocar mais um add-on no eventbrite de com + 10 pratas ganha um ingresso da algorave.
3 - Se vendermos pelo menos 600 ingressos, pagar do caixa do evento

É bom colocar um deadline pra tomar essa decisão se o sponsor não rolar.
