### ISSUE TITLE
Participação de 3 (três) servidores do MPTO

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2024-org#114]
### Descrição
Venda de ingresso para servidores do MPTO
https://pythonbrasil.freshdesk.com/a/tickets/11511

## Requisitos para a atividade ser considerada como concluída

- [x] Emitir proposta comercial
- [ ] Gerar voucher
- [ ] Responder email com voucher e proposta comercial
- [ ] Após o evento, gerar nota fiscal
- [ ] Após evento, enviar nota fiscal para cliente

**Comment by biancarosa** [comment]
esse é o mesmo que o do "Tribunal de Justiça do Estado de Rondônia - TJRO"? https://pythonbrasil.freshdesk.com/a/tickets/11421

**Comment by cecivieira** [comment]
Não. Essa é outra instituição

**Comment by biancarosa** [comment]
criei essa outra aqui: https://github.com/pythonbrasil/pybr2024-org/issues/122

**Comment by cecivieira** [comment]
@rochamrcs tu poderia responder a essa demanda? Chegou uma nova mensagem.
Se tiver alguma pendência para a APyB, por favor, comenta aqui.

**Comment by rochamrcs** [comment]
@cecivieira a nova mensagem é referente a issue #117

**Comment by rochamrcs** [comment]
@naanadr

**Comment by anicelysantos** [comment]
@rochamrcs te retorno amanhã com essa informação

**Comment by anicelysantos** [comment]
@rochamrcs neste link tu encontra a Certidão de falência e concordata: https://drive.google.com/drive/folders/1tYJfWZNCe_1jFJG7EDeJ7DsZ9-CC7oj5?usp=drive_link

Preciso que tu veja com eles, por favor, o que seria esse atestado de capacidade técnica para eu poder solicitar aqui. Se tiver um exemplo seria ótimo.

**Comment by rochamrcs** [comment]
@anicelysantos obrigado pelo retorno, enviei a certidão e tirei essa dúvida com eles. Vamos aguardar ☺️

**Comment by rochamrcs** [comment]
@anicelysantos me encaminharam esse como exemplo 
[ATESTADO DE CAPACIDADE TÉCNICA CURSO FOTOGRAFIA - Atestado de Capacidade Técnica _ Curso de Imagem Mobile_ FIEC Travessa da Imagem-3.pdf](https://github.com/user-attachments/files/17248113/ATESTADO.DE.CAPACIDADE.TECNICA.CURSO.FOTOGRAFIA.-.Atestado.de.Capacidade.Tecnica._.Curso.de.Imagem.Mobile_.FIEC.Travessa.da.Imagem-3.pdf)

**Comment by anicelysantos** [comment]
@rochamrcs legal! Pelo que vi do exemplo é basicamente incluir detalhes do serviço que está sendo fornecido para eles. Vocês podem fazer essa redação e me enviar em arquivo aberto que aqui eu coloco a logo da ApyB e assino.

**Comment by rochamrcs** [comment]
@anicelysantos Pesquisei mais um pouco e entendi que essa declaração precisa ser emitida por um "cliente" que já recebeu nossos "serviços". Nesse doc de exemplo tem o período em que foi executado o serviço. É possível conseguir o contato de alguém órgão público ou empresa privada para enviar esse atestado?

**Comment by anicelysantos** [comment]
Oi @rochamrcs estou dando uma sondada em algumas empresas. Te retorno assim que obter resposta.

**Comment by rochamrcs** [comment]
Oi @anicelysantos, dei um retorno negativo para eles informando que não conseguimos. Quando finalizar o evento vou solicitar as insitituições que participaram a declaração. Para termos disponivel nas proximas edições
