### ISSUE TITLE
Check-in de palestrantes [garantir uma boa experiencia de palestras no evento]

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#116]
Pedir numero de voo possivelmente, slidedeck pra segunda semana de outubro, de alguma forma criar um contato mais proximo com os palestrantes para auxiliar na montagem de palestras

**Comment by thaisviana** [comment]
Proposta de comunicação:

- [ ]  Email de confirmação de palestra aceita, com pedido pra aceite. (10/setembro)
- [ ]  Email pedindo minibio e foto para divulgação em redes sociais e oferencendo mentoria para construção e treino da palestra (12/setembro)
- [ ] Quem não. responder minibio e foto, insistir 2x e fazer repescagem liberando a vaga se necessario  [18/setembro]
- [ ] Mandar mais um email falando sobre a estrutura do palco e sobre a possibilidade de receber slide e colab ou jupyter notebook até 17/outubro para facilitar a vida da organização. Caso seja uma live coding muito especifica... pedir pra estar na arena para preparar o computador e alocar a palestra ou no primeiro horário ou na volta do almoço pra não atrapalhar as transições (2/outubro)
- [] Quem não responder o email a cima, insistir 2x e após fazer mais uma repescagem se necessário.

ps.: Esse acompanhamento de perto de palestrantes está sem responsável na organização
