### ISSUE TITLE
Criar arte e calendário de posts para atividades confirmadas

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#121]
### Descrição
https://talks.python.org.br/orga/event/pythonbrasil-2024/submissions/?q=&state=confirmed

**Comment by thaisviana** [comment]
- [ ]  arte criada (https://www.canva.com/design/DAGQNGt_aKA/A9FDlzAXhRim0ncnrcG88w/edit?utm_content=DAGQNGt_aKA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [ ]  posts programados no buffer
