### ISSUE TITLE
proposta comercial - ingressos - TJRO

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#122]
### Descrição
Venda de ingresso para servidores do Tribunal de Justiça do Estado de Rondônia - TJRO"

https://pythonbrasil.freshdesk.com/a/tickets/11421

### Requisitos para a atividade ser considerada como concluída

- [x] Emitir proposta comercial
- [ ] Gerar voucher
- [ ] Responder email com voucher e proposta comercial
- [ ] Após o evento, gerar nota fiscal
- [ ] Após evento, enviar nota fiscal para cliente

**Comment by rochamrcs** [comment]
Fiz uma proposta baseada na solicitação do TJRO. Você pode validar e ver se tem algum ponto que ficou sensível e precisa ser retirado ou ajustado? Nas propostas anteriores foi usado todos os dias do evento, mas como os tutoriais são livres e dependem de vaga, eu preferi retirar e deixar apenas as datas das palestras o que é contemplado pelo ingresso.

**Comment by cecivieira** [comment]
@rochamrcs massa
Tu poderia comentar aqui com o link para proposta?

**Comment by rochamrcs** [comment]
@cecivieira https://docs.google.com/document/d/1DIc6ZAqRVVwLOVC8NSevHjElBjht5MSiyQFqLN2BGDU/edit?usp=drivesdk

**Comment by cecivieira** [comment]
@rochamrcs inseri comentários no documento

**Comment by rochamrcs** [comment]
A compra foi realizada diretamente pelos Servidores.
