### ISSUE TITLE
Venda de ingresso para 3 funcionários do Banco do Brasil

### ISSUE THREAD

**Issue by eli-junior** [pythonbrasil/pybr2024-org#125]
Descrição
Venda de ingresso para 3 funcionários do Banco do Brasil

Requisitos para a atividade ser considerada como concluída

- [x] Emitir proposta comercial. Deve conter: 
    - Razão Social
    - CNPJ
    - Comprovante do optante do Simples Nacional ou, se for o caso, documento de isenção tributária
    - Endereço completo
    - Banco / número da agência / número da conta corrente com dígito (preferencialmente Banco do Brasil)
    - Código ISSQN que constará na Nota Fiscal
- [ ] Gerar voucher
- [ ] Responder e-mail com voucher e proposta comercial
- [ ] Após o evento, gerar nota fiscal
- [ ] Após evento, enviar nota fiscal para cliente

Obrigado

**Comment by eli-junior** [comment]
@biancarosa não sei se eu usei o fluxo correto... acabei criando uma issue direto por aqui...

se o fluxo for outro, por favor me avise! Obrigado!

**Comment by rochamrcs** [comment]
@eli-junior recebemos um email via eventbrite do Richard, ecaminhei a proposta para ele e para o email ditec.gesec.gestao@bb.com.br.
Me coloco a disposição.

**Comment by eli-junior** [comment]
Perfeito! Obrigado!

**Comment by rochamrcs** [comment]
A compra foi relizada diretamente pelo eventbrite
https://pythonbrasil.freshdesk.com/a/tickets/11626

**Comment by rochamrcs** [comment]
@cecivieira o Banco do Brasil solicitou 3 NFs para fazer o reembolso dos colaboradores que participaram do evento. Enviei a solicitação das NFs via ultradox

**Comment by cecivieira** [comment]
respondida

**Comment by rochamrcs** [comment]
@cecivieira Obrigado!
