### ISSUE TITLE
Algorave: divulgação nos canais oficias e chamada de artistas

### ISSUE THREAD

**Issue by diegodukao** [pythonbrasil/pybr2024-org#126]
### Descrição
Eu estou em contato com o Fábio da Jusbrasil e com o Léo do Galpão Ladeira das Artes para a realização da Algorave e está tudo certo para acontecer. Agora precisamos de artistas para tocar. Eu e Amieiro vamos preparar um set longo, mas o ideal seria ter pelo menos mais duas apresentações.

Queremos incentivar a prática do livecoding na comunidade Python, então a Algorave vai ser exclusiva para participantes da Python Brasil, tanto para assistir quanto para tocar. Não vamos chamar artistas que não estejam inscritos no evento. Teremos vaga para as pessoas que quiserem se inscrever durante o evento para tocar, mas é muito importante que tenhamos já algumas apresentações confirmadas antes do evento. Então precisamos fazer a chamada nos canais oficiais. 

### Requisitos para a atividade ser considerada como concluída
- Chamada para artistas nos canais oficiais da Python Brasil com um formulário para inscrição na Algorave

**Comment by biancarosa** [comment]
@diegodukao a algorave tem alguma identidade visual, logo, arte etc? 😉

**Comment by biancarosa** [comment]
vou vendo se consigo fazer algo com a identidade da pybr - e aí podemos juntar a logo da algorave se tiver ou algo assim!

**Comment by diegodukao** [comment]
@biancarosa tem só a logo. Eu não achei em alta, mas posso ver se alguem no grupo da Algorave Brasil tem. 

![image](https://github.com/user-attachments/assets/cb4d2563-ee36-4669-9e8e-b14224c90ff5)

https://upload.wikimedia.org/wikipedia/commons/2/25/Algorave_logo.png

**Comment by diegodukao** [comment]
@biancarosa  Será que rola de divulgar a algorave hoje ou amanhã? Fiz o form para a inscrição. Precisa de mais alguma coisa?
https://docs.google.com/forms/d/e/1FAIpQLSdKkTwoVusMxibwBsYIRXKX8TPZZQ7Ns7DecbCdfECrFXWgHA/viewform?usp=sf_link

**Comment by diegodukao** [comment]
Pra descrição pode ser o que tá na wikipedia: "An algorave (from an algorithm and rave) is an event where people dance to music generated from algorithms, often using live coding techniques"

**Comment by biancarosa** [comment]
Divulgação feita ❤️

**Comment by biancarosa** [comment]
Divulgação feita ❤️
