### ISSUE TITLE
Proposta comercial - 5 ingressos INPLAN RJ

### ISSUE THREAD

**Issue by rochamrcs** [pythonbrasil/pybr2024-org#131]
### Descrição
Venda de ingresso para servidores do INPLAN RJ
https://pythonbrasil.freshdesk.com/a/tickets/11699

## Requisitos para a atividade ser considerada como concluída

- [x] Emitir proposta comercial
- [ ] Gerar voucher
- [ ] Responder email com voucher e proposta comercial
- [ ] Após o evento, gerar nota fiscal
- [ ] Após evento, enviar nota fiscal para cliente

**Comment by rochamrcs** [comment]
@cecivieira foi solicitado a documentação abaixo:

Para a  formalização do processo de contratação e emissão da Nota de Empenho, solicito também,a gentileza,  de nos encaminhar  os documentos abaixo relacionados:

- Cópia do RG do representante legal (subscritor da proposta de preços e do contrato).
- Declaração de responsabilidade Civil e Administrativa (modelo anexo). Deverá constar a assinatura do representante legal da empresa.
- Prova de inscrição no Cadastro de Contribuinte Estadual ou Municipal relativa ao domicílio ou sede do proponente, pertinente ao seu ramo e compatível com o objeto contratual;
- ~~Contrato social ou estatuto social da empresa atualizado, com ata da eleição da última diretoria~~;
- Certidão de regularidade fiscal com o IPTU, se a empresa tiver estabelecimento no município do Rio de Janeiro. Não sendo proprietário do(s) imóvel (eis) ocupado(s) pela empresa, consta declaração de que não possui imóvel no Município do Rio de Janeiro e cópia do contrato que lhe permite o uso do imóvel (locação, cessão e uso);
- Certidão de regularidade fiscal com o ISS (Certidão Negativa do Imposto sobre Serviços)
- Prova de regularidade para com a Fazenda Federal e Estadual do domicílio ou sede do      licitante;
-
[2 Sequencia de documentacao empresa vencedora.docx](https://github.com/user-attachments/files/17085140/2.Sequencia.de.documentacao.empresa.vencedora.docx)
[1 Declaração de Responsabilização Civil e Administrativa.docx](https://github.com/user-attachments/files/17085145/1.Declaracao.de.Responsabilizacao.Civil.e.Administrativa.docx)

**Comment by cecivieira** [comment]
@anicelysantos tu consegue levantar essa documentação?

**Comment by anicelysantos** [comment]
Opa, consigo!

**Comment by anicelysantos** [comment]
@rochamrcs os documentos estão nesta pasta que já compartilhei contigo anteriormente: https://drive.google.com/drive/folders/1YVUgWGDntICx2x3epwia8UQoNuBANWVu

**Comment by rochamrcs** [comment]
Obrigado!

**Comment by rochamrcs** [comment]
Não recebemos retorno após o envio da documentação, então presumo que não irão prosseguir com a compra.
