### ISSUE TITLE
[Financeiro] Orçamento para camisas e swags

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#17]
Target: 1000 camisas

**Comment by biancarosa** [comment]
cotar por tam da estampa e qtd de cores

**Comment by vitorsantanna2** [comment]
Adicionei o orçamento para 1000 camisas feita pela rede Estampa lá no nosso drive(https://drive.google.com/drive/u/0/folders/107wguZUEKhmmz7ros6FD4abtebk_iaKF), eles conseguem fazer o mesmo preço independente da cor, eu me baseei no tamanho da estampa do ano passado.

E continuo no aguardo das respostas de outras empresas que entrei em contato.

**Comment by vitorsantanna2** [comment]
Adicionado o orçamento feito pela Dimona (https://drive.google.com/file/d/1cJ3dS3koL2Ts-KhqWSad0GPnJSad60Qe/view?usp=sharing), eles também garantem o mesmo preço independente da cor da camisa, esse valor orçado é para uma estampa de duas cores(que é o caso da logo da Python Brasil 2024).

**Comment by biancarosa** [comment]
temos um orçamento inicial, podemos enviar um pedido novamente qd tiver a arte antes mas a meta é revisitar em julho

**Comment by biancarosa** [comment]
<img width="480" alt="Screenshot 2024-03-24 at 19 05 08" src="https://github.com/pythonbrasil/pybr2024-org/assets/1480558/255653a7-60ee-435b-acec-91cb6b695e35">
% de camisas de cada tamanho baseado no ultimo evento

**Comment by biancarosa** [comment]
Seria bom aqui listarmos o os swags que queremos fazer, e em ordem, pra que a gente possa passar uma demanda p/ designer aqui
