### ISSUE TITLE
[Design] Primeira entrega da arte visual

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#2]
**Entrega número 1**

- Logo
- Fontes
- Post padrão pra divulgar em social media
- Esquema de cores
- Landing page do site

O ideal seriamos ter um orçamento base pra isso.

Deixando o @flaviocpontes como owner dessa issue, mas todos podem opinar.

**Comment by biancarosa** [comment]
Eu e Thais conversamos com a Lara, ela topou fazer a arte, orçamento flexível dependendo do nosso budget. Não sabemos nosso budget rs então precisamos descobrir.

**Comment by biancarosa** [comment]
Legal ver os comentários que o pessoal da apyb fez: #15, eles listaram coisas que podem ser legais de termos.

**Comment by jamesperes** [comment]
Itens iniciais para Outubro:
- Logo 
- Fontes/Cores
- Banner ( Rede Social)

**Comment by biancarosa** [comment]
Já fechamos com o Renan, basicamente só aguardar aqui até ele ter algo pronto pra iteragirmos. Deve estar pronto até fim de setembro.
