### ISSUE TITLE
[Financeiro] Pagar local do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2024-org#24]
[Contrato assinado](https://drive.google.com/file/d/1Oi6Skie9WXAt-3F60VhdAqNywFxJYCoY/view?usp=drive_link)

Valor Total: R$ 105.000,00 + R$ 3.800,00, referente ao adicional de serviços e energia, no domingo, 20/10,
das 8h às 18h.

- [x] VENCIMENTO DA 1ª NOTA FISCAL: 10/01/2024 / VALOR BRUTO: R$ 21.760,00
- [x] VENCIMENTO DA 2ª NOTA FISCAL: 29/01/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 3ª NOTA FISCAL: 29/02/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 4ª NOTA FISCAL: 29/03/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 5ª NOTA FISCAL: 29/04/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 6ª NOTA FISCAL: 29/05/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 7ª NOTA FISCAL: 29/06/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 8ª NOTA FISCAL: 29/07/2024 / VALOR BRUTO: R$ 10.880,00
- [x] VENCIMENTO DA 9ª NOTA FISCAL: 29/08/2024 / VALOR BRUTO: R$ 10.880,00

**Comment by cecivieira** [comment]
Solicitado pagamento da 1. parcela

**Comment by cecivieira** [comment]
Pagamento realizado @biancarosa precisa enviar o comprovante de pagamento para a contratada sempre??

**Comment by biancarosa** [comment]
Vou confirmar!

**Comment by biancarosa** [comment]
Solicitacao de pgto da nota que vencia em 29/01 feito, por algum motivo não chegou no nosso e-mail.

**Comment by cecivieira** [comment]
Pagamento da 3. parcela realizado

**Comment by biancarosa** [comment]
Solicitacao de pgto da nota que vence em 29/03 feito à APyB.

**Comment by biancarosa** [comment]
/remind VENCIMENTO DA 5ª NOTA FISCAL for 25/04/2024

**Comment by cecivieira** [comment]
Pagamento realizado

**Comment by cecivieira** [comment]
Se der pra empresa enviar a nota fiscal 1 semana antes do pagamento ou já emitir todas as outras, seria massa. Assim, a gente conseguiria programar os pagamentos na data certinha

**Comment by cecivieira** [comment]
pagamento realizado

**Comment by biancarosa** [comment]
acho que o erro é mais meu aqui, eles emitem a nota antes mas envio pra apyb muito encima da hora e vou mudar isso próx mês

**Comment by biancarosa** [comment]
cabou!
