### ISSUE TITLE
[Logística] Solicitar alvará de funcionamento do evento

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2024-org#25]
Ler orientações e preencher formulário:
https://services-carioca.rio.rj.gov.br/group/guest/alvara-de-eventos

Auxílio para Legalização de Eventos fornecido pelo local:
+55 21 98171-1144 / ‎+55 21 2137-5396 (Marcelo)

**Comment by vitorsantanna2** [comment]
Entrarei em contato.

**Comment by biancarosa** [comment]
Juntando docs, fizemos consulta prévia autorizada, e agora precisamos da autorização do corpo de bombeiros e vamos lá....

Com a autorização do corpo de bombeiros voltamos pra prefeitura e seguimos com o processo

**Comment by thaisviana** [comment]
Não rolou
