### ISSUE TITLE
[Logística] Compartilhar senhas com organização

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2024-org#26]
Passar senhas:
instagram, twitter, canva, mailchimp

Atribuir perfil ao:
linkedin e facebook (?)

Prazo: 18 jan. 2024

**Comment by cecivieira** [comment]
@rougeth temos algum chaveiro por onde compartilhamos as senhas das redes sociais e ferramentas usadas pelas organizações da pybr?

Se não houver, @naanadr tu poderia dá uma olhada em como poderíamos fazer isso? A Python Rio criou uma conta gratuita no 1Password (https://github.com/1Password/1password-teams-open-source)

**Comment by rougeth** [comment]
> @rougeth temos algum chaveiro por onde compartilhamos as senhas das redes sociais e ferramentas usadas pelas organizações da pybr?

Não temos. Eu não sabia que 1Password oferecia plano gratuito para comunidade!

**Comment by cecivieira** [comment]
@naanadr tu poderia dá uma olhada nisso?
A ideia é criar um chaveiro exclusivo para as organizações da PyBr.

Aparentemente é uma boa usar a conta gratuita do 1password para comunidades/projeto open source. O que tu acha? Alguns outra sugestão?

Quando tu criar o chaveiro, coloco as chaves dentro. Seria massa entregar isso até quinta para organização.

**Comment by naanadr** [comment]
@cecivieira vou dar uma olhada nisso

**Comment by naanadr** [comment]
@cecivieira a organização da pybr tem acesso ao email `eventos@python.org.br` ?

**Comment by rougeth** [comment]
> a organização da pybr tem acesso ao email eventos@python.org.br ?

Sim, tem acesso via Freshdesk.

**Comment by naanadr** [comment]
Já abri o PR e estou aguardando aprovação do 1Password. Por enquanto temos 14 dias de teste gratis e parece que eles estão demorando 2 semanas para revisar os PRs.

![image](https://github.com/apyb/tarefas/assets/21251472/956f8012-e35f-40c7-a3cb-6868c0ed3412) 

Apenas os emails da APyB tem acesso de admins e owners no time que eu criei. A ideia seria a org de 2024 passar os emails de quem precisa ter acesso, e eu adiciono ao time como usuário.

**Comment by cecivieira** [comment]
@naanadr 
adiciona no grupo, por favor:

- me@biancarosa.com.br
- thaisnviana@gmail.com
- cecivieira@gmail.com
- drumondaugusto@gmail.com
- tarsis.azevedo@gmail.com
- flaviocpontes@gmail.com

**Comment by naanadr** [comment]
convites enviados @cecivieira

**Comment by cecivieira** [comment]
@naanadr aceitei o convite, mas acho que ainda não tenho acesso para salvar senhas no cofre da Python Brasil ou eu só não sei fazer. 
Eu consigo visualizar o cofre, mas não visualizo como salvar senha nele para que todo o grupo possa ver.

**Comment by naanadr** [comment]
@cecivieira depois que voces aceitarem o convite para entrar no cofre, eu recebo um e-mail para habilitar que voces utilizem o cofre.

Ve se agora foi 😄

**Comment by cecivieira** [comment]
@naanadr conclui que não sei criar itens dentro de um cofre específico. Tu sabe? Como faz?

**Comment by naanadr** [comment]
@cecivieira 🤣 

1) Acesse a lista de vaults: 
![image](https://github.com/pythonbrasil/pybr2024-org/assets/21251472/6445e025-21f7-4ae9-9b35-c429e4b847fa)
2) Selecione o vault que você quer, nesse caso o da PyBR: 
![image](https://github.com/pythonbrasil/pybr2024-org/assets/21251472/df3149f8-4278-4c07-97c0-71f3e9f7250d)
3) Abra o vault: 
![image](https://github.com/pythonbrasil/pybr2024-org/assets/21251472/44977c53-55d0-4b51-a56c-9b782816c69f)
4) Agora é só adicionar algo no vault:
![image](https://github.com/pythonbrasil/pybr2024-org/assets/21251472/ae2b0072-3a10-4bf9-a083-a4d103232f31)


PS: Não vou mandar o link do vault aqui, porque é uma url sensível. Mas você pode salvar nos seus favoritos, para economizar clicks.

**Comment by naanadr** [comment]
@cecivieira você conseguiu adicionar items no vault?

Além disso, enviei os convites para os emails que você mandou anteriormente e os convites expiram em 5 dias. Como os convite anteriores já expiraram, reenviei eles.

Essas são as pessoas que faltam aceitar o convite:
![image](https://github.com/pythonbrasil/pybr2024-org/assets/21251472/cfaa21d2-2d0f-4ddb-96cb-4b1d974aeb54)

**Comment by cecivieira** [comment]
@naanadr eu não consigo chegar nessa tela. Quando tento adicionar uma senha, sou redirecionada para o meu cofre já existente, não para o da APyB.
Bora marcar um síncrono de 20min?

**Comment by cecivieira** [comment]
Inseri no cofre as senhas das redes sociais e algumas outras.

@biancarosa testa, por favor. Se der falta de alguma, avisa aqui na thread. Se eu lembra de outras, vou adicionando.

https://pythonbrasil.1password.com/
