### ISSUE TITLE
Ata - Reunião 16/01

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#29]
**Status updates**

- Local
- Plano de patrocínio

**Comment by biancarosa** [comment]
Idéia inicial do local (capacidade 1000 pessoas): podemos colocar octanorm nas salas e rezar pro audio nao vazar. mas a ideia inicial era pensar em trilha unica + outras coisas satelites no evento.

**Comment by vitorsantanna2** [comment]
Atualizar nome da issue para Ata - Reunião 16/01

**Comment by biancarosa** [comment]
trilha unica: 
-- reduz em 1/3 ou 1/4 a qtd de palestrantes. é um formato possível. 
-- podemos fazer palestras com aluguel de headset / fone.
-- mezzazino pode ter open space, com tv, algo bem organico!

open space:
-- open space é open space, não pode ser open space & palestra rolando ao msm tempo (DevOps Days). podemos experimentar isso. open space vs lightning talks?  
-- abertura em cxs do sul. podia colocar o nome no open space, na lightning talks.
