### ISSUE TITLE
[Comunicação] Atualizar identidade visual das redes sociais

### ISSUE THREAD

**Issue by cecivieira** [pythonbrasil/pybr2024-org#32]
### Descrição
Atualizar identidade visual das redes sociais

### Requisitos para a atividade ser considerada como concluída

- Instagram
- Twitter
- Facebook
- Linkedin

**Comment by cecivieira** [comment]
Aguardando conclusão da #26

**Comment by biancarosa** [comment]
Aberto aqui pra alguém pegar! @flaviocpontes topa pegar essa?

**Comment by cecivieira** [comment]
As senhas já foram inseridas no cofre. Essa task tá desbloqueada. Já pode seguir
