### ISSUE TITLE
[Financeiro] Traduzir Plano de Patrocínio para Inglês

### ISSUE THREAD

**Issue by tiidadavena** [pythonbrasil/pybr2024-org#34]
### Traduzir Plano de Patrocínio para Inglês
Traduzir o [plano de patrocínio](https://docs.google.com/presentation/d/19H6hYsFifCF73d60uGD7TSQnkBZq1DCFCCG3qn75_oI/edit#slide=id.g1ea6311bd2c_0_57) finalizado para inglês.

### Etapas

- [x] Pedir acesso ao [drive](https://drive.google.com/drive/u/2/folders/1uxhau4AQRE3543g1jOWov9kOaxS5cxyK)
- [x] Pedir acesso ao [Figma](https://www.figma.com/file/wCPLiyXgId08fnCI0apDeg/PYBR-RJ?type=design&node-id=0-1&mode=design&t=3WsBsVhPwVBKq7m3-0)
- [x] Duplicar o arquivo [PP](https://drive.google.com/drive/u/0/folders/1uxhau4AQRE3543g1jOWov9kOaxS5cxyK) adicionando prefixo [EN]
- [x] Compartilhar e avisar no grupo
- [x] Traduzir os textos no PP
- [x] Traduzir os textos criados através de imagens no [Figma](https://www.figma.com/file/wCPLiyXgId08fnCI0apDeg/PYBR-RJ?type=design&node-id=0-1&mode=design&t=3WsBsVhPwVBKq7m3-0)
- [x] Pedir revisão
- [x] Validar revisões
- [x] Subir para o repositório do site, colocando link ao lado do plano em pt-br
- [x] Avisar para o time de Patrocínio que está tudo pronto
- [x] Fechar esta issue

**Comment by tiidadavena** [comment]
Versão em inglês para avaliação: https://docs.google.com/presentation/d/1Jv0g5TMbboutXQmWvmbV_UMgjJpUfnB8/edit?usp=sharing&ouid=105194890272054172164&rtpof=true&sd=true

**Comment by biancarosa** [comment]
Alterado @tiidadavena, vou subir no site já! Se quiser validar uma última vez, só mexi em uma tradução que faltava e alterei as mencões a praça XV pra manter ou o nome original ou suprimir a menção.
