### ISSUE TITLE
[Reunião] Reunião geral: 28-02-2024

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#39]
# Reunião PyBR 2024
_ Definir cronograma das próximas ações
__ Lançamento do site / alteração nas redes sociais / chamada para patrocinadores
--- @biancarosa atualizar todos do status aqui.
__ Criação da página de inscrição do evento / definição do valores do ingressos
--- definição da plataforma (eventbrite ou outra)
--- @vitorsantanna2 atualizar sobre os orçamentos de camisa.
__ Cronograma de divulgação de keynotes.
--- note: @thaisviana consegue liderar isso?
__ Cronograma de C4P (envio de palestras)
--- note: @flaviocpontes consegue liderar aqui?

## Ata

- Fechar camisa em jul/2024, mas vale fazer um round de pedido de orçamento antes qd tivermos a arte.
- Ver alguem para contratar para cuidar das redes sociais do evento!

**Cronograma lightweight da reunião**
- Sugestões de Keynotes até 20/03
- "Decidir" os keynotes até 30/03
- C4P
--- 18/05 -> 28/05
--- v0 palestrantes definidos até 30/07

### Ações para serem realizadas
- [x] Bia pegar a tarefa #16 
- [x] @flaviopontes criar task do C4P
- [x] @thaisviana -> keynote

**Comment by flaviocpontes** [comment]
Pretalx is mine!
https://github.com/pretalx/pretalx
