### ISSUE TITLE
[Logística] Abrir call4papers do evento

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#40]
### Descrição

Abrir C4P usando pretalx, utilizando como base as perguntas descritas no comentário dessa issue.

O evento deve ser criado em https://talks.python.org.br. Ao pegar essa tarefa, enviar e-mail no pvt para @biancarosa criar o seu usuário dentro da equipe de administração do pretalx.

### Requisitos para a atividade ser considerada como concluída
- C4P aberto no pretalx :)
- Issue de divulgação do C4P nas redes sociais criadas aqui no repositório.

**Comment by anadulce** [comment]
Perguntas usadas nos anos anteriores.

**Pessoais - são importantes porque a PSF quer estatísticas de diversidade**

1 - Você é uma pessoa PCD?
Sim
Não
Prefiro não responder

2 - Se você respondeu sim, quais recursos de acessibilidade você vai precisar?
- Dissertativa opcional 

3 - Como você se identifica?
Homem
Mulher
Não-binárie
Outro
Prefiro não responder

4 - Se você marcou "Outros" na pergunta anterior, como você se identifica?
- Dissertativa opcional

5 - Faz parte da população T (Pessoa trans, Travesti)?
Sim
Não
Prefiro não responder

6 - Como você se define?
Uma pessoa amarela
Uma pessoa branca
Uma pessoa indigena
Uma pessoa parda
Uma pessoa preta
Prefiro não responder

7 - Orientação sexual
Assexual
Bissexual
Gay
Hétero
Lésbica
Pansexual
Prefiro não responder

8 - Onde você mora?
Estados brasileiros
América Latina
Fora da América Latina

**Carreira: A PSF também quer saber o nível de experiência dos nossos palestrantes, por isso a gente pergunta.**

9 - Você programa em Python? Disclaimer: isso não é um critério avaliativo, apenas queremos conhecer as pessoas que ministram atividades no nosso evento.
Não programo, minha atividade é sobre outro tema (exemplo: carreira ou pessoas)
Não programo em Python, minha atividade é sobre outras tecnologias
Sim, há menos de um ano
Sim, há menos de três anos
Sim, há menos de cinco anos
Sim, há menos de dez anos
Sim, há mais de dez anos

10 - Como você considera sua experiência com a linguagem Python? Isso não é um critério avaliativo também :)
Nula :)
Iniciante
Intermediária
Avançada

**Pergunta pra saber se essa pessoa tem uma relação com a Python Brasil, isso normalmente significa que ela entende melhor sobre a comunidade, CDC, etc, pode ser um bom critério de desempate**

11 - Essa é a sua primeira vez participando da Python Brasil?
Sim :)
Participei da Python Brasil 2023 em Caxias do Sul - RS
Participei da Python Brasil 2022 em Manaus - AM
Participei da Python Brasil 2021 - Online 
Participei da Python Brasil 2020 - Online
Participei da Python Brasil 2019 em Ribeirão Preto - SP
Participei da Python Brasil 2018 em Natal - RN
Participei da Python Brasil 2016 em Florianópolis - SC
Participei da Python Brasil 2017 em Belo Horizonte - MG
Participei da Python Brasil de 2015 em São José dos Campos - SP
Participei da Python Brasil 2013 em Brasília - DF
Participei da Python Brasil 2014 em Porto de Galinhas - PE
Participei da Python Brasil 2012 em Rio de Janeiro - RJ
Participei de edições anteriores a 2012

** Perguntas pra entender se essa pessoa tem experiência ministrando e ajuda nos termos de renovação de palestrantes (não é interessante ter sempre as mesmas pessoas no palco, embora tenha acontecido muito por pura falta de opção)**

12 - Você já ministrou atividades em uma edição da Python Brasil?
Não
Em 2020 ou anos anteriores
Em 2021 
Em 2022
Em 2023

12 - Já ministrou alguma atividade em algum outro evento?
Não :)
Meetups e eventos locais
Eventos online
Eventos com até 200 pessoas
Eventos com até 1000 pessoas
Eventos internacionais
Eventos com mais de 1000 pessoas

**Comment by anadulce** [comment]
Termos

Declaro ciência do termo de consentimento para tratamento de dados pessoais
Conforme artigo 5º, inciso X, da Lei Geral de Proteção de Dados Pessoais (nº 13.709/2018), entende-se por "tratamento" a coleta, produção, recepção, classificação, utilização, acesso, reprodução, transmissão, distribuição, processamento, arquivamento, armazenamento, eliminação, avaliação ou controle da informação, modificação, comunicação, transferência, difusão ou extração.  Em atendimento ao artigo 8º, parágrafo 4º, este formulário guarda finalidade determinada, sendo esta:      • Cadastro de submissão de atividade para PyBR2024.  Após o encerramento da Python Brasil 2024, os dados pessoais constantes nas submissões serão eliminados.

Declaro ciência do uso e divulgação da imagem
A Python Brasil 2024 será transmitida e gravada, então ao marcar este checkbox você autoriza a Python Brasil a utilizar e veicular os vídeos referidos e as outras mídias de divulgação no site da organização na Internet, nas redes sociais, pôsteres de divulgação da Python Brasil 2024 a serem veiculados no Brasil e/ou no exterior a fim de publicidade institucional.

Você conhece e concorda em respeitar o Código de Conduta da Python Brasil durante todo o evento?
É esperado que todas pessoas presentes no evento leiam e concordem com o Código de Conduta da Python Brasil (https://python.org.br/cdc). Em particular para as pessoas proponentes: todo conteúdo da atividade, sejam os slides ou quaisquer outros, deve ser apropriados para uma audiência profissional. Linguagem ou imagens de conotação sexual, não são apropriados, nem linguagem ou imagens que difamem ou diminuam pessoas baseadas em raça, gênero, religião, orientação sexual, aparência física ou desabilidade.

**Comment by biancarosa** [comment]
Essas perguntas são além do form padrão do pretalx, certo?

**Comment by anadulce** [comment]
**Perguntas para avaliação do conteúdo: são especialmente importantes para a nossa curadoria.** 
Aqui um ponto muito importante é fixar o tamanho mínimo e máximo das respostas, porque quando forçamos as pessoas a escreverem um mínimo, elas nos fornecem respostas melhores e até pensam melhor em suas submissões. 
Essas perguntas são específicas para tutoriais e palestras, sprints não são avaliadas, apenas passam por uma validação de conformidade com a proposta (às vezes recebemos propostas que não configuram sprints).

1 - Descreva mais prolixamente o que será abordado na sua atividade, a sua motivação para criá-la e informações que considere relevantes.
Esse conteúdo será utilizado apenas na sua avaliação (não será divulgado), portanto não poupe detalhes que considere que são diferenciais da sua atividade. Outro ponto importante: a avaliação das atividades da Python Brasil é anonimizada, portanto você não deve colocar links ou realizar citações que exibam seu nome e/ou imagem.

2 - Tabela de conteúdo
Gostaríamos que nos fornecesse um esboço dos tópicos que serão abordados em sua atividade, eles serão utilizados apenas na avaliação da atividade (não serão divulgados). Atente-se ao tempo proposto da atividade, incluindo o tempo de perguntas. Por exemplo, considerando uma palestra:<br/> * 3 mins apresentando palestrante;<br/> * 3 mins contextualizando problema motivador;<br/> * 10 mins embasamento teórico;<br/> * 3 mins apresentando a biblioteca A;<br/> * 9 mins apresentando B;<br/> * 3 mins explicando C;<br/> * 9 mins conclusões;<br/> * 5 mins para dúvidas;<br/> Além disso, lembre-se que a avaliação das atividades da Python Brasil é <b>anonimizada<b/>, portanto você não deve colocar links ou realizar citações  que exibam seu nome e/ou imagem.

3 - Quais conhecimentos prévios são necessários para que seja possível acompanhar bem a sua atividade?
Procure especificar essa parte: dizer apenas “Python Intermediário” não ajuda muito. Informar o nível de experiência e o tipo de conceito (pessoas, tecnologia) ou ferramenta (banco de dados SQL, desenvolvimento web, estatística, etc…)  necessário para conseguir acompanhar sua apresentação. Isso também nos ajudará a montar uma programação que tenha uma boa variedade de conteúdo para pessoas com diferentes interesses e níveis de conhecimento.

4 - O que as pessoas que participarem podem esperar aprender na sua atividade?
Qual expectativa as pessoas devem ter em relação ao conteúdo que você apresentará?

5 - Escolha até 3 palavras-chave para representar sua atividade:
Exemplo: Web, Testes, Data Science, IA, Pessoas, Carreira, DevOps

**Perguntas específicas de tutoriais.** É possível atrelar uma pergunta a um determinado tipo de atividade (se precisar de ajuda com isso, tamos aí).

1 - Quantas pessoas você se sente confortável em orientar?
Tutoriais são atividades práticas, que ocorrerão em laboratórios de informática, para um número restrito de pessoas, pois é esperado que a pessoa facilitadora consiga tirar dúvidas e conduzir o conteúdo.

**Perguntas específicas de sprints**
1 - Como o projeto contribui com a comunidade?
2 - Você faz parte do time de mantenedores do projeto?
3 - Qual o site ou repositório do projeto?

**Perguntas opcionais para divulgação**
1 - @ do Twitter
2 - @ do Instagram
3 - página do LinkedIn

**Comment by allanacardoso** [comment]
boa noite, estou desenvolvendo essa tas
