### ISSUE TITLE
[Logística] Sugestão e escolha de keynotes

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#41]
Criar uma votação no nosso grupo do telegram com os resultados do form: https://docs.google.com/forms/d/1rLQ-Y17e74zOe6Db4RiNTwviNYs_TuDTBULWcT-ROLs/edit

**Comment by biancarosa** [comment]
Seria legal criar uma chamada pública para chamada de keynotes aqui!

**Comment by rochamrcs** [comment]
Forms disponibilizado para votação: https://forms.gle/i8MQUMwGgPmitBmh7

**Comment by biancarosa** [comment]
done!
