### ISSUE TITLE
[Organização] Mover conteudo da pasta PyBR 2024 para a pasta da APyb

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#42]
### Descrição
Temos 2 pastas hoje, a idéia é consolidar. Não vou postar os links por segurança (são fechados, mas vai que...) então por favor perguntar no grupo.

### Requisitos para a atividade ser considerada como concluída

- Conteudo da pasta PyBR 2024 dentro da pasta da APyB.

**Comment by vitorsantanna2** [comment]
Tarefa concluída com sucesso, todos os arquivos foram migrados para dentro da pasta da APyB.
