### ISSUE TITLE
[Parcerias] Conversar com alguns hotéis das redondezas da BolsaRio e tentar negociar descontos (e conseguir o primeiro hotel!)

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#45]
### Descrição
Conversar com alguns hotéis das redondezas da BolsaRio e tentar negociar:
* Desconto para participantes. Algum código de desconto pra colocar no nosso site ou no email de compra de ingressos.
* Desconto no pacote de contratação de 6 quartos.

Hoteis cogitados na reunião:
1. Windsor Guanabara
2. Ibis Centro
3. Vila Galé Lapa
4. Selina Lapa

### Requisitos para a atividade ser considerada como concluída

Desconto fechado e publicado no site & redes sociais.

**Comment by biancarosa** [comment]
@rochamrcs comentou que tem alguns contatos na rede hoteleira.

eu entrei em contato com o Windsor Guanabara via formulario na pagina deles.

**Comment by rochamrcs** [comment]
Adicionado na pasta a apresentação para revisão da org:

https://docs.google.com/presentation/d/1fjt7WXhqdH9adriazsjJ6WlZ53lr3sh97DcIJLXnEUs/edit?usp=drive_link

Próximo passo, entrar em contato para agendar uma reunião.

**Comment by biancarosa** [comment]
Temos aí uns 5 emails de possiveis propostas! Esclarecer algumas informações com as propostas. Hoteis até agora não pediram exclusividade.
