### ISSUE TITLE
Adicionar demografia do evento no plano de patrocínio

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#47]
### Descrição

Precisamos saber dos dados:

% de pessoas de fora do estado do evento
adicionar dados de 2023
% de estudantes
nível de experiencia

github.com/pythonbrasil/dados

### Requisitos para a atividade ser considerada como concluída

*Por exemplo: "- Plano de patrocínio em PDF salvo no Drive da organização."*

- Verificar [acessibilidade das cores](https://www.toptal.com/designers/colorfilter/). Válido para atividades que dependem de imagem, como criação de artes e modificação do site.
- Item 1
- Item 2
- Item 3

**Comment by rochamrcs** [comment]
@biancarosa adicionei um planilha na pasta do plano de patrocínio com os dados demográficos.

https://docs.google.com/spreadsheets/d/1dtaCQ_-BA20TN_bIF8gt_UBRYyD198XBnc4I67WXzqc/edit?usp=drive_link

**Comment by biancarosa** [comment]
boa!

eu acabei usando os dados que ja tinha do script aqui: https://github.com/biancarosa/pybr-dados/blob/biancarosa/notebook/notebooks/Untitled.ipynb mas esse pode ser util ainda pra outros tipos de analises.

adicionei no plano em pt-br, faltando apenas add no plano em ingles!

**Comment by biancarosa** [comment]
adicionado no plano em ingles
