### ISSUE TITLE
[Patrocinio] Pedido de grant para a PSF

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#51]
### Descrição

- Copiar os docs do pedido de patrocínio do ano passado.
- Usar o budget plan criado na issue #63.

### Requisitos para a atividade ser considerada como concluída

- Pedido de grant enviado para a PSF.

**Comment by vitorsantanna2** [comment]
https://docs.google.com/document/d/1W3E2Ad1YzIPYop2kmOwTKDvoBj-wEfN3Relse2xmW3g/edit#heading=h.lx6ze08lfb0o

Esse é o template de pedido de patrocínio do ano de 2022.
De resumo, com base nesse template e com base nas informações da página da PSF, a gente precisa ter um link para a programação, um link para a inscrição, um link para o plano de patrocínio e um link para os patrocinadores(ou potenciais patrocinadores).

**Comment by rochamrcs** [comment]
Pedido enviado, aprovado e patrocinio recebido :)
