### ISSUE TITLE
Criar uma proposta de contrato com os termos da parceria com a FIAP

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#53]
### Descrição

Precisamos criar um contrato com a FIAP sobre a parceria da pybr com eles. Dados no google docs: https://docs.google.com/document/d/15YSxHbAzYUrTKbLvDfsFqSJRIFjJSoN4Ch_5fXGBUqk.

### Requisitos para a atividade ser considerada como concluída

- Draft to contrato com a FIAP para @biancarosa enviar.

**Comment by Thiago-Vargas** [comment]
Bia! Boa tarde.

Segue uma primeira minuta:



TERMO DE PARCERIA

 

Pelo presente instrumento particular:

 

I – PYTHON BRASIL XXXXXXX, doravante denominado “PYTHON BRASIL”

 

II – FIAP, xxxx, doravante denominado “FIAP”

 

(isoladamente denominadas como PARTE, e, em conjunto, denominadas PARTES).

 

Resolvem celebrar o presente Termo de Parceria, em conformidade com os termos e condições estipulados a seguir:

 

CLÁUSULA PRIMEIRA – DO OBJETO

 

1.1. O presente termo tem por objeto uma parceria no evento denominado “Python Brasil 2024”, o qual ocorrerá nos dias 16 à 21 de outubro de 2024, no Centro de Convenções Bolsa do Rio, Edifício Bolsa do Rio, Praça XV de Novembro, nº 20, Centro – Rio de Janeiro/RJ.

 

1.2. A denominação do evento poderá sofrer alteração a ser definida oportunamente pela PYTHON BRASIL.

 

CLÁUSULA SEGUNDA – DOS COMPROMISSOS DAS PARTES

 

2.1. Em contrapartida da presente parceria, a PYTHON BRASIL se compromete a (i) Disponibilizar à FIAP, o total de 05 (cinco) ingressos para o evento, cujas datas deverão ser definidas pela FIAP; (ii) Caso haja autorização expressa dos participantes, individualmente, os dados serão disponibilizados para FIAP; (iii) Divulgar, em suas redes sociais, agradecimento à FIAP pelo apoio no evento; (iv) Incluir a logo da FIAP no website do evento como parceiro; (v) Disponibilizar xxx brindes do evento (ecobag / papeis informativos); (vi) Disponibilizar 01 (um) tutorial de até 4h no dia 17/10, referente a um tema relevante ao ecossistema da comunidade Python; e (vii) Participação no evento principal.

 

2.2. Em contrapartida da presente parceria, a FIAP se compromete a disponibilizar o uso dos espaços da escola de negócios do SEBRAE através de parceria com a FIAP nos dias 16, 17 e 21 de outubro de 2024, das 09hs às 18hs ("Lounge FIAP").

 

            2.2.1. O espaço deverá ser constituído de (i) 01 (um) auditório com capacidade para 100 (cem) pessoas; (ii) 01 (uma) sala com capacidade para 50 (cinquenta) pessoas; (iii) 02 (duas) salas com capacidade para 25 (vinte e cinco) pessoas; e (iv) lounge que interligue as salas e áreas comuns.

 

CLÁUSULA TERCEIRA – DO PRAZO

 

3.1. O prazo da presente parceria, perdurará até que sejam satisfeitas as obrigações de ambas as PARTES, sendo seu início previsto para o dia 16 de outubro de 2024 e sua finalização em 21 de outubro de 2024.

 

CLÁUSULA QUARTA – DISPOSIÇÕES FINAIS

 

4.1. O presente instrumento poderá ser ampliado a qualquer momento, desde que de comum acordo entre as PARTES, mediante assinatura de um Termo Aditivo.

 

CLÁUSULA QUINTA – FORO

 

5.1. As partes elegem o Foro da Comarca da Capital do Estado do Rio de Janeiro para dirimir eventual demanda decorrente da presente parceria.

 

CLÁUSULA SEXTA – ASSINATURA ELETRÔNICA

 

6.1. Nos termos da legislação vigente, as PARTES expressamente concordam em utilizar e reconhecem como válida a comprovação de anuência aos termos ora acordados em formato eletrônico, incluindo assinaturas eletrônicas em plataforma eleita pelas PARTES, ainda que não utilizem de certificado digital emitido no padrão ICP-Brasil. A formalização das avenças na maneira supra acordada será suficiente para a validade e integral vinculação das partes ao presente instrumento.

 

E, por estarem justas e acertadas, as Partes assinam o presente termo de rescisão em duas vias de igual teor e forma, na presença das duas testemunhas abaixo subscritas, para que se produzam todos os efeitos de lei e de direito.

**Comment by biancarosa** [comment]
Joguei no doc! tá excelente

**Comment by biancarosa** [comment]
https://docs.google.com/document/d/1ZSKQj24HP8Ge-GdlWlvmz60o9tlc13_m2UCezXM90JE/edit
