### ISSUE TITLE
Deixar clara política de meia entrada no ingresso no eventbrite

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#54]
### Descrição
Política de meia entrada não está clara no eventbrite. Esclarecer.

O site da eventim tem um bom material. Seguimos as leis nacionais, do estado do RJ e da cidade do RJ.

https://help.eventim.com.br/hc/pt-br/articles/10227945761943-Leis-de-meia-entrada-v%C3%A1lidas-em-todo-o-pa%C3%ADs
https://help.eventim.com.br/hc/pt-br/articles/10227969798935-Leis-de-meia-entrada-para-eventos-na-regi%C3%A3o-Sudeste

### Requisitos para a atividade ser considerada como concluída

- Política de meia entrada precisa estar clara para compradores do ingresso.

**Comment by Thiago-Vargas** [comment]
Bia!! Eu gostaria de ajudar nesse ponto! Não co segui localizar a versão atual em Word. 😀

**Comment by Thiago-Vargas** [comment]
c) Professores e profissionais da Rede Pública Municipal de Ensino do Estado do Rio de Janeiro: Carteira Funcional emitida pela Secretaria Municipal de Educação e Documento de Identidade original (RG) ou cópia autenticada.

 

d) Garis da Companhia Municipal de Limpeza Urbana: crachá ou documento de identificação profissional, emitido pelo órgão competente acompanhado de documento oficial de identificação civil com foto.

 

e) Estudantes: Deverão apresentar a carteira de identificação estudantil (CIE) conforme modelo nacionalmente padronizado, expedida pela Associação Nacional de Pós-Graduandos (ANPG), União Nacional dos Estudantes (UNE), União Brasileira dos Estudantes Secundaristas (UBES) ou entidades filiadas, de acordo com a Lei Federal nº 12.933/2013.

 

f) Idosos: Deverão apresentar documento oficial de identificação com foto que comprove a idade igual ou superior a 60 anos.

 

g) Pessoas com deficiência: Cartão de Benefício de Prestação Continuada da Assistência Social da Pessoa com Deficiência ou de documento emitido pelo Instituto Nacional do Seguro Social - INSS que ateste a aposentadoria de acordo com os critérios estabelecidos na Lei Complementar nº 142, de 8 de maio de 2013. No momento de apresentação, esses documentos deverão estar acompanhados de documento de identidade oficial com foto.

 

h) Jovens de baixa renda: Carteira de Identidade Jovem emitida pela Secretaria Nacional de Juventude, acompanhada de documento de identidade oficial com foto.

 

4. Validade: A meia-entrada será válida para evento denominado Python Brasil 2024, que será realizado nos dias 16 à 20 de outubro de 2024, no Centro de Convenções Bolsa do Rio, localizado na Praça Quinze de Novembro, 20 - Centro, Rio de Janeiro - RJ, 20010-010, e sua concessão está sujeita à disponibilidade de ingressos destinados à meia-entrada, de acordo com a capacidade do local.

 

5. Disposições Gerais: Esta política está em conformidade com as leis estaduais e federais que regulamentam o direito à meia-entrada, e entra em vigor na data de sua publicação e revoga eventuais disposições anteriores que contrariem suas disposições.

**Comment by biancarosa** [comment]
@Thiago-Vargas sentindo falta dos itens a e b aqui!

**Comment by Thiago-Vargas** [comment]
Política de Meia-Entrada

 

1. Objetivo: Esta política visa regulamentar o direito à meia-entrada para estudantes, idosos, pessoas com deficiência e jovens de baixa renda, de acordo com a legislação vigente.

 

2. Beneficiários: Terão direito à meia-entrada: a) Menores de 21 anos, nos termos da Lei Estadual nº 3.364/2000; b) Profissionais que estejam em efetivo exercício e aposentados nas instituições de ensino, tanto os da rede estadual como os da rede privada, nos termos da Lei Estadual nº 8.775/2020; c) Professores e profissionais da Rede Pública Municipal de Ensino do Estado do Rio de Janeiro, nos termos da Lei Municipal nº 3.424/2002 e Lei Municipal nº 5.844/2015; d) Garis da Companhia Municipal de Limpeza Urbana, nos termos da Lei Municipal nº 8.251/2024; e) Estudantes regularmente matriculados em instituições de ensino público ou privado, desde a educação infantil até o ensino superior, nos termos da Lei Federal nº 12.933/2013; f) Cidadãos com idade igual ou superior a 60 anos (Idosos), nos termos da Lei Federal nº 12.933/2013; g) Pessoas com deficiência, nos termos da Lei Federal nº 12.933/2013; e h) Jovens de baixa renda, nos termos da Lei Federal nº 12.933/2013.

 

3. Documentação:

 

a) Menores de 21 anos: Documento de Identidade oficial com foto, expedido por órgão público e válido em todo território nacional, original ou cópia autenticada.

 

b) Profissionais que estejam em efetivo exercício e aposentados nas instituições de ensino, tanto os da rede estadual como os da rede privada: contracheque ou carteira funcional emitida pelo respectivo órgão empregador. Para profissionais aposentados, mediante apresentação de documento oficial emitido pelo órgão responsável.

 

c) Professores e profissionais da Rede Pública Municipal de Ensino do Estado do Rio de Janeiro: Carteira Funcional emitida pela Secretaria Municipal de Educação e Documento de Identidade original (RG) ou cópia autenticada.

 

d) Garis da Companhia Municipal de Limpeza Urbana: crachá ou documento de identificação profissional, emitido pelo órgão competente acompanhado de documento oficial de identificação civil com foto.

 

e) Estudantes: Deverão apresentar a carteira de identificação estudantil (CIE) conforme modelo nacionalmente padronizado, expedida pela Associação Nacional de Pós-Graduandos (ANPG), União Nacional dos Estudantes (UNE), União Brasileira dos Estudantes Secundaristas (UBES) ou entidades filiadas, de acordo com a Lei Federal nº 12.933/2013.

 

f) Idosos: Deverão apresentar documento oficial de identificação com foto que comprove a idade igual ou superior a 60 anos.

 

g) Pessoas com deficiência: Cartão de Benefício de Prestação Continuada da Assistência Social da Pessoa com Deficiência ou de documento emitido pelo Instituto Nacional do Seguro Social - INSS que ateste a aposentadoria de acordo com os critérios estabelecidos na Lei Complementar nº 142, de 8 de maio de 2013. No momento de apresentação, esses documentos deverão estar acompanhados de documento de identidade oficial com foto.

 

h) Jovens de baixa renda: Carteira de Identidade Jovem emitida pela Secretaria Nacional de Juventude, acompanhada de documento de identidade oficial com foto.

 

4. Validade: A meia-entrada será válida para evento denominado Python Brasil 2024, que será realizado nos dias 16 à 20 de outubro de 2024, no Centro de Convenções Bolsa do Rio, localizado na Praça Quinze de Novembro, 20 - Centro, Rio de Janeiro - RJ, 20010-010, e sua concessão está sujeita à disponibilidade de ingressos destinados à meia-entrada, de acordo com a capacidade do local.

 

5. Disposições Gerais: Esta política está em conformidade com as leis estaduais e federais que regulamentam o direito à meia-entrada, e entra em vigor na data de sua publicação e revoga eventuais disposições anteriores que contrariem suas disposições.

**Comment by Thiago-Vargas** [comment]
Verdade Bia! Kkk

Agora a versão completa!!😀😀
