### ISSUE TITLE
[Logística] Fechar o local do evento

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#7]
1000 a 1500 pax
Data a definir

**Comment by thaisviana** [comment]
Solicitar orçamento : 
- [ ] Armazem 3 Av. Rodrigues Alves, 73 - Centro, Rio de Janeiro - RJ; 
- [ ] NovoHotel(Centro) ; 
- [ ] Pier Maua;
- [ ] Mourisco**
- [ ]  MAM
- [ ]  MAR
- [ ]  Museu do Amanhã
- [ ]  Solar Real
- [ ]  expomag

**Comment by biancarosa** [comment]
Pra solicitar orçamento precisamos de data

**Comment by biancarosa** [comment]
Datas:
-- 1a opção: 18, 19 e 20 de outubro, considerar 2-4 dias depois (pref) ou antes para sprints e/ou tutoriais
-- 2a opção: 11, 12, e 13 de outubro, considerar 2-4 dias depois (pref) ou antes para sprints e/ou tutoriais.

**Comment by biancarosa** [comment]
Minimo 1 sala q comporte 1k

**Comment by cecivieira** [comment]
Definido local do evento:
 Salão do Paço
do CCBR - Centro de Convenções Bolsa do Rio, localizado na Rua do Mercado, 12, Centro-RJ.

contrato assinado: https://drive.google.com/file/d/1Oi6Skie9WXAt-3F60VhdAqNywFxJYCoY/view?usp=drive_link

**Comment by cecivieira** [comment]
Oi Renata, Feliz Ano Novo!

Estamos agrupando nossas dúvidas e vamos seguir com a assinatura e pagamento assim que entendermos esses pontos.

Seguem nossas dúvidas:

Limpeza:
1. A limpeza do espaço de eventos e dos banheiros e area de coffee break está incluída no contrato?

Montagem:
2. No contrato está escrito que a montagem não foi contratada. Isso significa que o posicionamento das cadeiras será feito pela organização?
3. O horário de montagem do palco 360 e a disposição da cadeira não está explicito no contrato, mas na visita, foi mencionado que como a cenografia é parceria exclusiva, vocês disponibilizavam o horário pra montagem de banner e palco 2 horas antes do evento e que esse tempo costuma ser o suficiente, e até, se não estiver locado no dia anterior, a empresa de cenografia poderia montar no dia anterior. Temos como deixar isso explicito no contrato?

Dependencias Alugadas:
4. No contrato temos apenas o Salão do Paço, no entanto o Mezanino do Paço é onde será servido o coffee break e estarão os stands de patrocinadores. Podemos deixar explicito na proposta essa área?
5. Na visita, vimos três salas de apoio que podem ser utilizadas pela organização, elas também não estão listadas no contrato. Podemos incluí-las?

Autorização Municipal e Autorização dos Bombeiros para evento de pequeno porte entre 300 e 2 mil pessoas:
6. Este tamanho de evento precisa de alvará?
7. Precisaremos de ambulância?
8. Vocês possuem os contatos para que possamos regularizar o evento?

Beijos, fico no aguardo

**Comment by cecivieira** [comment]
Limpeza:
1. A limpeza do espaço de eventos e dos banheiros e area de coffee break está incluída no contrato? Sim

Montagem:
2. No contrato está escrito que a montagem não foi contratada. Isso significa que o posicionamento das cadeiras será feito pela organização? Correto, entregaremos o salão montado no dia do evento.
3. O horário de montagem do palco 360 e a disposição da cadeira não está explicito no contrato, mas na visita, foi mencionado que como a cenografia é parceria exclusiva, vocês disponibilizavam o horário pra montagem de banner e palco 2 horas antes do evento e que esse tempo costuma ser o suficiente, e até, se não estiver locado no dia anterior, a empresa de cenografia poderia montar no dia anterior. Temos como deixar isso explicito no contrato? Uma vez que os equipamentos audiovisuais e cenografia serão contratados com o nossa parceira exclusiva, Brazil Cenarium, a montagem será feita de acordo com a nossa disponibilidade.

Dependencias Alugadas:
4. No contrato temos apenas o Salão do Paço, no entanto o Mezanino do Paço é onde será servido o coffee break e estarão os stands de patrocinadores. Podemos deixar explicito na proposta essa área? Sim
5. Na visita, vimos três salas de apoio que podem ser utilizadas pela organização, elas também não estão listadas no contrato. Podemos incluí-las? Sim

Autorização Municipal e Autorização dos Bombeiros para evento de pequeno porte entre 300 e 2 mil pessoas:
6. Este tamanho de evento precisa de alvará? Sim, porém Não exigimos
7. Precisaremos de ambulância? Não exigimos, porém é aconselhável ter.
8. Vocês possuem os contatos para que possamos regularizar o evento? Não exigimos a legalização do evento, mas indicamos:
 
Legalização de Eventos
+55 21 98171-1144 / ‎+55 21 2137-5396 (Marcelo)
