### ISSUE TITLE
Criar um guia da cidade

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#71]

**Comment by rochamrcs** [comment]
## Passeios:

- Praias 🏖️
- Parque Lajes
- Parque das Ruinas

## Cultura:

- Museu Naval
- Museu Histórico Nacional
- CCBB
- Real Gabinete Português de Leitura
- Paço Imperial

## Rolezinho
- Mureta da Urca
- Bafo da prainha
- Lapa
- Feira de São Cristovão

**Comment by rochamrcs** [comment]
Versão preliminar 

https://busy-authority-b34.notion.site/Guia-da-Cidade-9f77f731d8cc40daa2a058bcd9cc0abd?pvs=74
