### ISSUE TITLE
Ideias de posts para o blog.pythonbrasil.org.br

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#75]
- O que são sprints
- O que são tutoriais
- Dias de palestra 
- Oficinas
- O que estamos fazendo a nível de inclusão 
- Como contribuir
- Aonde se hospedar 
- Aonde comer
- Aonde festejar

**Comment by rochamrcs** [comment]
- Como foi sua primeira PYBR
- Dicas de como aproveitar ao maximo o evento
