### ISSUE TITLE
Conseguir entre 2-4 parcerias com hoteis alem do inicial (B&B)

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#77]
### Descrição
1 em negociação que é o Prodigy

+ espaço pra 3 hoteis - Cintia/Raquel como responsaveis

**Comment by rochamrcs** [comment]
Parceria com o Prodigy Santos Dumont confirmada!

Promo Code 10% - "PYBR2024"

Sem reserva cortesia

**Comment by biancarosa** [comment]
vamos fechar aqui :) já estamos bem com relacão a isso. precisamos focar nas outras coisas.
