### ISSUE TITLE
[Financeiro] Plano de patrocínio

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#8]

**Comment by cecivieira** [comment]
plano de patrocínio: https://docs.google.com/presentation/d/19H6hYsFifCF73d60uGD7TSQnkBZq1DCFCCG3qn75_oI/edit#slide=id.p

**Comment by cecivieira** [comment]
Falta:

- criar tabela comparativa entre cotas
- criar visualização demográfica
- revisar texto

**Comment by cecivieira** [comment]
@flaviocpontes

**Comment by rochamrcs** [comment]
Realizei alguns ajustes na apresentação, porem não alterei o arquivo original.

Coloquei uma cópia do editado na pasta: https://docs.google.com/presentation/d/1WW-BP92ZdS8rQNo36lSq86FetBR88cLQ/edit#slide=id.p1

Não consegui fechar a tabela comparativa, também fiquei devendo a visualização demográfica.

**Comment by rochamrcs** [comment]
[x] criar tabela comparativa entre cotas

**Comment by rochamrcs** [comment]
Link do figma aonde estão os textos e a tabela comparativa, caso precisem editar alguma coisa:

https://www.figma.com/file/wCPLiyXgId08fnCI0apDeg/PYBR-RJ?type=design&mode=design&t=L639Jvn5PysVK3T9-1

**Comment by biancarosa** [comment]
v1, done, obrigada @rochamrcs pelo figma e pelo trabalho aqui!
