### ISSUE TITLE
Verificar a instância onde está o evento

### ISSUE THREAD

**Issue by allanacardoso** [pythonbrasil/pybr2024-org#81]
### Descrição
*As perguntas não estão obedecendo a ordem que colocamos. Ao ordenar elas tornam a ficar embaralhadas*

### Requisitos para a atividade ser considerada como concluída

*Precisa debugar a instância*

**Comment by biancarosa** [comment]
fechado em favor dessa issue, no repo de mantenedores do pretalx da comunidade br -> https://github.com/comunidade-python-br/talks/issues/2
