### ISSUE TITLE
[Divulgação Patrocínio] Lincoln Loop

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#82]
### Descrição

- [x] Logo no site
- [x] Paragrafo de redes sociais enviado pela empresa
- [x] Parceria postada no linkedin
- [x] Parceria postada no twitter
- [x] Parceria postada no facebook
- [x] Parceria postada no instagram
- [x] Paragrafo do email enviado pela empresa
- [ ] Parceria enviada na lista de email

### Requisitos para a atividade ser considerada como concluída
- Parceria divulgada.

**Comment by biancarosa** [comment]
Arte criada

![lincoln loop](https://github.com/pythonbrasil/pybr2024-org/assets/1480558/f663f6d5-e0e4-4287-b887-5945a3e17044)

canva: https://www.canva.com/design/DAGIbHys0r0/kShZ13Y9UmoK1yUejUhfqA/edit

**Comment by biancarosa** [comment]
Lincoln Loop builds and maintains mission-critical Django applications that scale. Since 2007, their emphasis on pragmatic solutions and agile development has helped numerous startups and high-traffic sites grow their businesses. Lincoln Loop offers end-to-end services led by seasoned developers, from strategy and full-stack development to DevOps and comprehensive support.

A Lincoln Loop se especializa na construção e manutenção de aplicações Django de alto impacto e escalabilidade. Desde 2007, nossa abordagem voltada para soluções pragmáticas e desenvolvimento ágil tem apoiado startups e sites de alto tráfego na expansão de seus negócios. Oferecemos serviços completos, conduzidos por uma equipe de desenvolvedores experientes, abrangendo desde a estratégia e o desenvolvimento full-stack até DevOps e suporte contínuo.

**Comment by thaisviana** [comment]
deixei agendado pra amanhã o post  linkedin , instagram e fb.

Fica faltando twitter e lista de email que tem que ser feito na mão

**Comment by biancarosa** [comment]
eu botei no twitter la
