### ISSUE TITLE
Retificação de NF

### ISSUE THREAD

**Issue by Thiago-Vargas** [pythonbrasil/pybr2024-org#83]
Pessoal, hoje eu solicitei a emissão de uma NF para a empresa BEEMON TECNOLOGIA LTDA., CNPJ: 48.496.171/0001-80, no valor total de R$ 1.296,00. Esse valor é a soma dos valores de 6 ingressos de meia entrada no eventbrite (R$ 216,00 cada).

Ocorre que, o cliente perguntou se o pagamento poderia ser feito diretamente via PIX, e eu considerei que o pagamento seria realizado via eventbrite como os demais. 

Assim o valor correto é R$ 1.200,00 (R$ 200,00 cada ingresso).

Como faço para solicitar que a NF seja emitida no valor de R$ 1.200,00 e não no valor de R$ 1.296,00, conforme solicitado por equivoco, pela https://www.ultradox.com/app/apyb-solicitacao-nfe.

Abs!

**Comment by Thiago-Vargas** [comment]
@cecivieira ! Tks

**Comment by cecivieira** [comment]
@Thiago-Vargas nota emitida com a retificação solicitada.
