### ISSUE TITLE
Divulgar evento em locais relacionados

### ISSUE THREAD

**Issue by naanadr** [pythonbrasil/pybr2024-org#87]
### Descrição

Visando fugir um pouco das bolhas das redes sociais, que limitam o nosso alcance. O intuito dessa atividade é levantar possíveis canais alternativos, como e-mails de coordenações de cursos de TI, e coletivos de inserção de pessoas na área de tecnologia. E após ter esses canais levantados, entrar em contato com eles divulgando o evento.

**Comment by naanadr** [comment]
- Casa fluminence
- DataLabe

**Comment by tiidadavena** [comment]
> * [Casa Fluminense](https://casafluminense.org.br/)
> 
>     * [DataLabe](https://datalabe.org/)

@anicelysantos conhece alguns pontos de contato

**Comment by naanadr** [comment]
Estou listando aqui possíveis contatos para receberem desconto na inscrição do evento, em troca de oferecer divulgação do evento em sua base. Ficou decidido que será ofertado um desconto de 10% para comunidades/coletivos de tecnologia.

## Coletivos que trabalham com minorias sociais cariocas

Esses coletivos talvez sejam mais legíveis para receber os 10 ingressos gratuitos. 

### [Casa Fluminense](https://casafluminense.org.br/)
- casa[at]casafluminense.org.br

### [data_labe](https://datalabe.org/)
- polinho[at]datalabe.org
- contato[at]datalabe.org

### [Observatório de Favelas](http://www.observatoriodefavelas.org.br/)
- contato[at]observatoriodefavelas.org.br

## Coletivos que buscam incluir pessoas mais diversas na comunidade de tecnologia

### [PretaLab_](https://www.pretalab.com/)
- comunidade[at]olabi.org.br

### [Minas Programam](https://minasprogramam.com/)
- contato[at]minasprogramam.com

### [progra{m}aria](https://www.programaria.org/)
- helloworld[at]programaria.org

### [reprograma](https://reprograma.com.br/)
- info[at]reprograma.com

### [Laboratoria](https://www.laboratoria.la/br)
- ulia.diniz[at]laboratoria.la
- infosp[at]laboratoria.la

### [WoMakersCode](https://womakerscode.org/)
- contato[at]womakerscode.org

## Coletivos em geral

### [LinuxTips](https://www.linuxtips.io/)
- contato[at]linuxtips.io

### [Data Hackers](https://www.datahackers.com.br/)
- falecom[at]datahackers.com.br

### [Google Developers Group Brasil](https://www.instagram.com/gdgbrasil/)
Entrei em contato pelo instagram, para entender qual o e-mail que eles utilizam

### [OpenSanca](https://opensanca.com.br/)
Talvez o publico seja o mesmo do Grupy-Sanca 🤔 
- opensanca[at]gmail.com

### [Orange Juice](https://tech.orangejuice.com.br/orangejuice)
- contato[at]orangejuice.com.br

### [Data Science Academy](https://www.datascienceacademy.com.br/)
- suporte[at]datascienceacademy.com.br
- pagamento[at]datascienceacademy.com.br

### [Rocketseat](https://www.rocketseat.com.br/)
- oi[at]rocketseat.com.br

### [TOTVS Developers](https://developers.totvs.com/)
- developers[at]totvs.com

**Comment by naanadr** [comment]
Enviei e-mail pelo Freshdesk para todos esses possíveis parceiros e irei acompanhar por possíveis respostas.

**Comment by julianafalves** [comment]
@naanadr você pode compartilhar um template desse e-mail? To elaborando um e-mail para mais possíveis parceiros também.

**Comment by naanadr** [comment]
@julianafalves o e-mail que eu enviei para as pessoas:

```
Olá!

Faço parte da equipe de organização da Python Brasil 2024, a maior conferência sobre a linguagem de programação Python da América Latina. A PyBR é um evento itinerante e organizado de forma totalmente voluntária pela comunidade, estamos rodando o Brasil divulgando um pouco mais sobre Python em formato de palestras, workshops, tutoriais, entre outras atividades. 

Esse ano estamos trazendo o evento para o Rio de Janeiro, e ele acontecerá entre os dias 16 e 21 de outubro, com atividades online e presenciais. Em nossas [redes sociais](https://linktr.ee/pythonbrasil) já começamos a divulgar algumas pessoas convidadas (keynotes) e estamos com submissões de palestras abertas até o dia 10 de agosto. Mais informações sobre o evento, vocês podem encontrar no site [2024.pythonbrasil.org.br](https://2024.pythonbrasil.org.br/). 
 
O que vocês acham de fazermos uma parceria? Podemos oferecer um cupom de 10% de desconto na compra de qualquer ingresso, mais divulgação de vocês como nossos parceiros, em troca gostaríamos de sua ajuda divulgando a conferência internamente por via de suas newsletter/grupos/redes sociais.

Caso vocês tenham interesse em sermos parceiros, poderiam responder esse e-mail com a logo de vocês em alta resolução e fundo transparente?

Atenciosamente,
```

**Comment by naanadr** [comment]
Comunidades que até então firmarão parceria com a gente:

* Mulheres em Dados
* Orange Juice
* Linux Tips
* Data Hackers

Todas as logos estão disponíveis no [drive](https://drive.google.com/drive/folders/1fP628EUbnS5FaV6ONfpQ93yosWAiMBGK?usp=sharing). Quando tiver mais próximo do evento irei fazer um post falando das parceiras.

**Comment by naanadr** [comment]
A maioria das comunidades ainda não me deram retorno, irei entrar em contato com elas pelas redes sociais já com 
a arte de divulgação do evento e o código de desconto, as que me retornarem irei pedir a logo da comunidade para que eu possa depois fazer uma arte geral de divulgação das parceiras. 

Redes sociais que irei entrar em contato:

### [PretaLab_](https://www.pretalab.com/)
- [Instagram](https://www.instagram.com/pretalab_/)

### [Minas Programam](https://minasprogramam.com/)
- [Instagram](https://www.instagram.com/minasprogramam/)

### [progra{m}aria](https://www.programaria.org/)
- [Instagram](https://www.instagram.com/programaria/)

### [reprograma](https://reprograma.com.br/)
- [Instagram](https://www.instagram.com/reprogramabr/)

### [Laboratoria](https://www.laboratoria.la/br)
- [Instagram](https://www.instagram.com/laboratoria_br/)

### [WoMakersCode](https://womakerscode.org/)
- [Instagram](https://www.instagram.com/womakersgram/)

### [MariaLab](https://www.marialab.org/)
- [Instagram](https://www.instagram.com/marialab_org/)

### [Data Science Academy](https://www.datascienceacademy.com.br/)
- [Instagram](https://www.instagram.com/dsacademybr/)

### [Rocketseat](https://www.rocketseat.com.br/)
- [Instagram](https://www.instagram.com/rocketseat/)

### [Escola de Dados](https://escoladedados.org/)
- [Instagram](https://www.instagram.com/escoladedadosbr/)

**Comment by naanadr** [comment]
Mensagem que irei enviar para as parceiras:

```
Olá!

Somos a Python Brasil 2024, a maior conferência sobre a linguagem de programação Python da América Latina. A PyBR é um evento itinerante e organizado de forma totalmente voluntária pela comunidade, estamos rodando o Brasil divulgando um pouco mais sobre Python em formato de palestras, workshops, tutoriais, entre outras atividades. 

Esse ano estamos trazendo o evento para o Rio de Janeiro, e ele acontecerá entre os dias 16 e 21 de outubro, com atividades online e presenciais. Aqui no nosso Instagram você pode encontrar mais informações sobre a programação do evento. 

O que vocês acham de fazermos uma parceria? Podemos oferecer um cupom de 10% de desconto (INSERIR_O_CUPOM_DA_COMUNIDADE) na compra de qualquer ingresso, mais divulgação de vocês como nossos parceiros, em troca gostaríamos de sua ajuda divulgando a conferência internamente por via de suas newsletter/grupos/redes sociais.

Caso vocês tenham interesse em sermos parceiros, você pode utilizar a arte abaixo com essa descrição de base:

"""
A Python Brasil 2024 (@pythonbrasil) já tem data e local certos! O evento acontecerá entre os dias 16 e 21 de outubro, na cidade do Rio de Janeiro, com atividades online e presenciais. No perfil do evento você pode encontrar mais informações sobre a programação do evento.
​
​Para as nossas pessoas seguidoras, temos uma surpresa! Você pode adquirir o seu ingresso com 10% de desconto utilizando o cupom INSERIR_O_CUPOM_DA_COMUNIDADE. 
​
​Mais informações sobre o evento, acesse o link na bio da @pythonbrasil.

#python #pybr #pythonbrasil #techcomunity #tecnologia #pythonbrasil2024
""" 

Aguardando um retorno de vocês.
Abraços,
Maria Fernanda.
```

**Comment by naanadr** [comment]
Para as parceiras já confirmadas irei enviar a seguinte mensagem:

```
Olá, Pessoal!

Viemos falar que a programação da Python Brasil saiu essa semana, e com ela gostaríamos de compartilhar com vocês mais uma arte para ajudar na divulgação do evento, e reforçar o código promocional de 10% que as pessoas membras da sua comunidade tem direito de uso. 

A nova arte de divulgação está em anexo, e caso precisem de mais alguma coisa, estamos a disposição.

Abraços,
Maria Fernanda.
```
