### ISSUE TITLE
Definir cronograma e datas para o form de ingressos sociais

### ISSUE THREAD

**Issue by biancarosa** [pythonbrasil/pybr2024-org#99]

**Comment by anadulce** [comment]
@biancarosa preciso de algumas informações complementares para poder definir pontos nessa issue, o mais importante é: temos uma quantidade de ingressos?
Se sim, quantos por cento (ou quantidade exata) destinada ao PyLadies e AfroPython?
Temos algum direcionamento sobre públicos que gostaríamos de atingir? Ou essa proposta deve partir de mim?

Sugestão de datas:
* Dia 04 de setembro - levar primeiro lote de pessoas aprovadas na minha curadoria para revisão na reunião;
* Dia 05  de setembro - enviar primeira chamada de pessoas aprovadas;
* Dia 17 de setembro - data limite para retirada dos ingressos do primeiro lote;
* Dia 18 de setembro - levar segundo lote de pessoas aprovadas na minha curadoria para revisão na reunião;
* Dia 19 de setembro - enviar segunda chamada de pessoas aprovadas;
* Dia 01 de outubro - data limite para retirada dos ingressos do segundo lote;
* Dia 02 de outubro - levar terceiro lote de pessoas aprovadas na minha curadoria para revisão na reunião;
* Dia 03 de outubro - enviar terceira chamada de pessoas aprovadas;

Sobre a priorização: talvez seja pelos contextos onde o forms foi divulgado, mas quase a totalidade dos preenchimentos refletem os grupos que gostaríamos de atingir. Nesse contexto, eu tenho uma tendência a aprovar a grande maioria dos casos.
